{
    "v1": {
        "datasource": "DataSourceNoCloud [seed=/var/lib/cloud/seed/nocloud-net]",
        "init": {
            "errors": [],
            "finished": 2.46,
            "recoverable_errors": {},
            "start": 1.76
        },
        "init-local": {
            "errors": [],
            "finished": 0.51,
            "recoverable_errors": {},
            "start": 0.38
        },
        "modules-config": {
            "errors": [],
            "finished": 2.77,
            "recoverable_errors": {},
            "start": 2.64
        },
        "modules-final": {
            "errors": [
                "('scripts_user', RuntimeError('Runparts: 1 failures (runcmd) in 1 attempted commands'))"
            ],
            "finished": 2.97,
            "recoverable_errors": {
                "WARNING": [
                    "Failed to run module scripts_user (scripts in /var/lib/cloud/instance/scripts)",
                    "Running module scripts_user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed"
                ]
            },
            "start": 2.92
        },
        "stage": null
    }
}
